### PR TITLE
create output directories in script, not with .gitkeep

### PR DESCRIPTION
**Pull request by wjchulme**
When a script is run that saves a file to a directory, that directory must first exist. `git` doesn't track directories, so the directory must either already exist because there is a tracked file in it (using an empty `.gitkeep` file by convention), or the directory must be created as part of the script itself. This PR switches from the first approach to the second approach.

### CODE REVIEW

**Review by rebkwok — APPROVED** [review]

**Review by evansd — APPROVED** [review]
This looks fine, just two questions from looking at the R docs here:
https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/files2

>  `dir.create` indicates failure if the directory already exists

What does "indicates failure" mean here? Presumably it doesn't actually throw an error which stops execution as we would have hit this problem before now. But are there any other bad consequences of "indicating failure"?

By default this only creates the last element of the path, so if `output` didn't exist it would fail. In this particular case that's not a problem because `output` will always exist by the time we get here, but I think it would be good practice to use the `recursive = TRUE` option so that if someone changed the path to `output/plots/by_stp` or something it would still work.

**Comment by wjchulme** [comment]
"indicating failure" means it shows a warning that the directory couldn't be created or already exists, it doesn't fail. Which really it should if it can't create a directory that doesn't exist.

We should probably recommend using `fs::dir_create(dir)` everywhere instead, because

1. it's "recursive" by default
2. it doesn't show warnings if the directory already exists
3. it fails if it _can't_ create the directory
4. it has better cross-platform credentials

the `fs` package is already installed in the R docker image

**Comment by evansd** [comment]
:+1: `fs::dir_create(dir)` sounds _much_ better to me

**Comment by wjchulme** [comment]
https://github.com/opensafely/os-demo-research/pull/32

**Comment by inglesp** [comment]
Might've got the wrong end of the stick here, but it output files are specified in project.yaml, could cohort-extractor create the directories automatically?

**Comment by evansd** [comment]
We did discuss this, but it doesn't work for patterns like `foo/*/bar.csv`. (And I think you mean job-runner rather than cohort-extractor, right?)

**Pull request merged**
